spring:
  datasource:
    name: newbee_mall
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimeZone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    url: jdbc:mysql://localhost:3306/newbee_mall?useUnicode=true&serverTimezone=UTC
    username: root
    password: 1111
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.newbee.mall.entity